### ISSUE TITLE
Some glitch on second page

### ISSUE THREAD

**Issue by Serenade600** [mikemahoney218/quarto-tandf#1] opened 2022-09-11 02:21 UTC
The html  https://mike.quarto.pub/demo-taylor-and-francis-template/ has some glitch on second page
![image](https://user-images.githubusercontent.com/40297752/189509187-59efcbdc-1198-4810-8f5d-a34bda526d06.png)

**Comment by mikemahoney218** [comment] 2022-09-11 19:37
Thanks; I can't seem to reproduce this locally (rendering this on my own PC looks as you'd expect) but I do also see it in the demo PDF. I'll keep looking.

**Comment by mikemahoney218** [comment] 2022-12-11 14:10
Thanks for the report! This seems to be fixed with newer versions of Quarto, and is now fixed on the demo.

**Closed as completed by mikemahoney218** 2022-12-11 14:10 UTC
